### ISSUE TITLE
Ability to forward headers from API request to Imgproxy endpoint

### ISSUE THREAD

**Issue by kevcube** [BitPatty/next-image-s3-imgproxy-loader#140]
We would like to be able to forward the `accept` header (and possibly others) from users to our Imgproxy endpoint.

I see `forwardedHeaders`, but my understanding of this parameter is that those are headers which are added from the Imgproxy instance to the response.

We're looking for the reverse, some list of parameters that can be added from the API request to the imgproxy request.

**Comment by kevcube** [comment]
I am checking out the codebase to possibly PR this in.

I also encountered another issue starting the `.devcontainer` in vscode, making a second issue about that.

**Comment by BitPatty** [comment]
Fixed with #142
