### ISSUE TITLE
Next.js 15 compatibility

### ISSUE THREAD

**Issue by barrenechea** [BitPatty/next-image-s3-imgproxy-loader#612]
It's funny that I asked the same for Next.js 14 in https://github.com/BitPatty/next-image-s3-imgproxy-loader/issues/432 😄 

Next 15 was recently released, and while attempting to upgrade the same project, it is failing because of the peer `next@"^13.0.0 || ^14.0.0"` statement. Is there any chance you could take a look? I'm unsure if it would be just adding `^15.0.0` in there.

Thank you in advance!

**Comment by BitPatty** [comment]
Hi Sebastian,
Thanks for the heads-up :)
I extended the scope in v0.13.0.

**Comment by barrenechea** [comment]
Working wonderfully, thank you very much! :D
